# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-02-05 05:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20200205_1407'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_hour', models.CharField(max_length=10, verbose_name='Working Time Per Day')),
            ],
        ),
        migrations.RemoveField(
            model_name='book',
            name='publication_date',
        ),
        migrations.AddField(
            model_name='book',
            name='pulication_date',
            field=models.DateField(blank=True, null=True, verbose_name='Publish Date'),
        ),
    ]
